name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distribution packages
        run: python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/vietlott-data
    # Job-level permissions override the workflow-level permissions block.
    # Ensure the job keeps `contents: read` (needed for download-artifact) and
    # also allows `id-token: write` for OIDC-based publishing if used.
    permissions:
      contents: read
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Use a PyPI API token stored in repository secrets. Create a secret
        # named `PYPI_API_TOKEN` with a token from https://pypi.org/manage/account/
        # The recommended `user` for API tokens is the literal string "__token__".
        with:
          user: "__token__"
          password: ${{ secrets.PYPI_API_TOKEN }}
